package commands

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/bramp/assets/internal/manifest"
	"github.com/bramp/assets/internal/render"
)

type outputRule struct {
	Target string
	Source string
	Output manifest.Output
}

type errWriter struct {
	w   *bufio.Writer
	err error
}

func newErrWriter(w io.Writer) *errWriter {
	return &errWriter{w: bufio.NewWriter(w)}
}

func (w *errWriter) WriteString(s string) {
	if w.err != nil {
		return
	}
	_, w.err = io.WriteString(w.w, s)
}

func (w *errWriter) Flush() error {
	if w.err != nil {
		return w.err
	}
	return w.w.Flush()
}

// RunGen prints a deterministic Makefile fragment for declared outputs.
func RunGen(args []string, stdout io.Writer, stderr io.Writer) int {
	fs := flag.NewFlagSet("gen", flag.ContinueOnError)
	fs.SetOutput(stderr)

	manifestPath := fs.String("manifest", "assets.yaml", "Path to assets manifest")
	if err := fs.Parse(args); err != nil {
		return 1
	}
	if fs.NArg() != 0 {
		_, _ = fmt.Fprintf(stderr, "gen: unexpected positional arguments: %v\n", fs.Args())
		return 1
	}

	m, err := manifest.LoadFile(*manifestPath)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "gen: failed to load manifest %q: %v\n", *manifestPath, err)
		return 1
	}

	if err := renderMakefileFragment(stdout, m); err != nil {
		_, _ = fmt.Fprintf(stderr, "gen: failed to write output: %v\n", err)
		return 1
	}
	return 0
}

func renderMakefileFragment(w io.Writer, m *manifest.Manifest) error {
	rules := collectOutputRules(m)
	out := newErrWriter(w)

	appendGenHeader(out, rules)

	for _, r := range rules {
		appendRule(out, m, r)
	}

	appendGenFooter(out)

	return out.Flush()
}

func appendGenHeader(w *errWriter, rules []outputRule) {
	files := collectRuleTargets(rules)

	w.WriteString("# Generated by assets gen. DO NOT EDIT.\n")
	w.WriteString("# Commands below are commented examples for readability in this file.\n")
	w.WriteString("# Actual execution is performed via assets build --target <output>.\n")
	w.WriteString("GENERATED_ASSET_FILES :=")
	if len(files) > 0 {
		w.WriteString(" ")
		w.WriteString(strings.Join(files, " "))
	}
	w.WriteString("\n\n")
}

func collectRuleTargets(rules []outputRule) []string {
	files := make([]string, 0, len(rules))
	for _, r := range rules {
		files = append(files, r.Target)
	}
	return files
}

func appendRule(w *errWriter, m *manifest.Manifest, r outputRule) {
	w.WriteString(r.Target)
	w.WriteString(": ")
	w.WriteString(r.Source)
	w.WriteString("\n")
	appendRuleCommentCommands(w, m, r)
}

func appendGenFooter(w *errWriter) {
	w.WriteString("\n")
	w.WriteString("assets.lock: $(GENERATED_ASSET_FILES)\n")
}

func collectOutputRules(m *manifest.Manifest) []outputRule {
	rules := make([]outputRule, 0)
	for _, a := range m.Assets {
		for _, o := range a.Outputs {
			rules = append(rules, outputRule{Target: o.Path, Source: a.Source, Output: o})
		}
	}

	// Keep generated output stable regardless of manifest order so tests and
	// checked-in fragments remain deterministic.
	sort.Slice(rules, func(i, j int) bool {
		if rules[i].Target == rules[j].Target {
			return rules[i].Source < rules[j].Source
		}
		return rules[i].Target < rules[j].Target
	})

	return rules
}

func appendRuleCommentCommands(w *errWriter, m *manifest.Manifest, r outputRule) {
	steps, err := render.ResolvePipelineWithOptions(
		m,
		r.Source,
		r.Output,
		// Gen emits host-agnostic commented examples for the declared pipeline,
		// not the locally available tool subset, so output stays deterministic.
		render.ResolveOptions{CheckAvailability: false},
	)
	if err != nil {
		// Keep unresolved notes as plain comments, not make recipes.
		w.WriteString("  # unresolved: ")
		w.WriteString(err.Error())
		w.WriteString("\n")
		return
	}

	commands := render.PlannedCommands(steps, render.BuildContext{
		InputPath:  r.Source,
		OutputPath: r.Target,
		Width:      r.Output.Width,
		Height:     r.Output.Height,
		ScaleMode:  r.Output.Options.ScaleMode,
		Background: r.Output.Options.Background,
		TmpPath:    "__tmp1__",
		Tmp2Path:   "__tmp2__",
	})
	for _, command := range commands {
		appendWrappedCommentCommand(w, command)
	}
}

func appendWrappedCommentCommand(w *errWriter, command string) {
	// Use non-tab comment lines so make does not treat these as recipes.
	parts, ops := splitCommandChain(command)
	if len(parts) == 0 {
		w.WriteString("  #\n")
		return
	}

	w.WriteString("  # ")
	w.WriteString(parts[0])
	w.WriteString("\n")

	for i, part := range parts[1:] {
		op := "&&"
		if i < len(ops) {
			op = ops[i]
		}
		w.WriteString("  # ")
		w.WriteString(op)
		w.WriteString(" ")
		w.WriteString(part)
		w.WriteString("\n")
	}
}

// splitCommandChain breaks a shell command into comment-friendly segments at
// top-level chaining tokens so generated example commands are easier to read.
//
// The returned ops align with parts[1:], allowing callers to re-render a
// multi-step command as one commented line per step without changing the
// original command text.
func splitCommandChain(command string) ([]string, []string) {
	if command == "" {
		return nil, nil
	}

	parts := make([]string, 0, 4)
	ops := make([]string, 0, 3)
	remaining := command

	for {
		idx, token := nextChainToken(remaining)
		if idx < 0 {
			parts = append(parts, strings.TrimSpace(remaining))
			break
		}

		parts = append(parts, strings.TrimSpace(remaining[:idx]))
		op := strings.TrimSpace(token)
		op = strings.ReplaceAll(op, " ", "")
		ops = append(ops, op)
		remaining = remaining[idx+len(token):]
	}

	if len(parts) > 0 && parts[0] == "" {
		parts[0] = command
	}

	return parts, ops
}

func nextChainToken(s string) (int, string) {
	tokens := []string{" && ", " || ", " | "}
	bestIdx := -1
	bestToken := ""

	for _, token := range tokens {
		idx := strings.Index(s, token)
		if idx >= 0 && (bestIdx == -1 || idx < bestIdx) {
			bestIdx = idx
			bestToken = token
		}
	}

	return bestIdx, bestToken
}
