package commands

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/bramp/assets/internal/manifest"
)

type outputRule struct {
	Target string
	Source string
}

func RunGen(args []string, stdout io.Writer, stderr io.Writer) int {
	fs := flag.NewFlagSet("gen", flag.ContinueOnError)
	fs.SetOutput(stderr)

	manifestPath := fs.String("manifest", "assets.yaml", "Path to assets manifest")
	if err := fs.Parse(args); err != nil {
		return 1
	}
	if fs.NArg() != 0 {
		_, _ = fmt.Fprintf(stderr, "gen: unexpected positional arguments: %v\n", fs.Args())
		return 1
	}

	m, err := manifest.LoadFile(*manifestPath)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "gen: failed to load manifest %q: %v\n", *manifestPath, err)
		return 1
	}

	_, _ = io.WriteString(stdout, renderMakefileFragment(m))
	return 0
}

func renderMakefileFragment(m *manifest.Manifest) string {
	rules := collectOutputRules(m)

	files := make([]string, 0, len(rules))
	for _, r := range rules {
		files = append(files, r.Target)
	}

	var b strings.Builder
	b.WriteString("# Generated by assets gen. DO NOT EDIT.\n")
	b.WriteString("GENERATED_ASSET_FILES :=")
	if len(files) > 0 {
		b.WriteString(" ")
		b.WriteString(strings.Join(files, " "))
	}
	b.WriteString("\n\n")

	for _, r := range rules {
		b.WriteString(r.Target)
		b.WriteString(": ")
		b.WriteString(r.Source)
		b.WriteString("\n")
	}

	return b.String()
}

func collectOutputRules(m *manifest.Manifest) []outputRule {
	rules := make([]outputRule, 0)
	for _, a := range m.Assets {
		for _, o := range a.Outputs {
			rules = append(rules, outputRule{Target: o.Path, Source: a.Source})
		}
	}

	sort.Slice(rules, func(i, j int) bool {
		if rules[i].Target == rules[j].Target {
			return rules[i].Source < rules[j].Source
		}
		return rules[i].Target < rules[j].Target
	})

	return rules
}
