package commands

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/bramp/assets/internal/manifest"
	"github.com/bramp/assets/internal/render"
)

type outputRule struct {
	Target string
	Source string
	Output manifest.Output
}

func RunGen(args []string, stdout io.Writer, stderr io.Writer) int {
	fs := flag.NewFlagSet("gen", flag.ContinueOnError)
	fs.SetOutput(stderr)

	manifestPath := fs.String("manifest", "assets.yaml", "Path to assets manifest")
	if err := fs.Parse(args); err != nil {
		return 1
	}
	if fs.NArg() != 0 {
		_, _ = fmt.Fprintf(stderr, "gen: unexpected positional arguments: %v\n", fs.Args())
		return 1
	}

	m, err := manifest.LoadFile(*manifestPath)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "gen: failed to load manifest %q: %v\n", *manifestPath, err)
		return 1
	}

	_, _ = io.WriteString(stdout, renderMakefileFragment(m))
	return 0
}

func renderMakefileFragment(m *manifest.Manifest) string {
	rules := collectOutputRules(m)

	files := make([]string, 0, len(rules))
	for _, r := range rules {
		files = append(files, r.Target)
	}

	var b strings.Builder
	b.WriteString("# Generated by assets gen. DO NOT EDIT.\n")
	b.WriteString("# Commands below are commented examples for readability in this file.\n")
	b.WriteString("# Actual execution is performed via assets build --target <output>.\n")
	b.WriteString("GENERATED_ASSET_FILES :=")
	if len(files) > 0 {
		b.WriteString(" ")
		b.WriteString(strings.Join(files, " "))
	}
	b.WriteString("\n\n")

	for _, r := range rules {
		b.WriteString(r.Target)
		b.WriteString(": ")
		b.WriteString(r.Source)
		b.WriteString("\n")
		appendCommentedCommands(&b, m, r)
	}

	b.WriteString("\n")
	b.WriteString("assets.lock: $(GENERATED_ASSET_FILES)\n")

	return b.String()
}

func collectOutputRules(m *manifest.Manifest) []outputRule {
	rules := make([]outputRule, 0)
	for _, a := range m.Assets {
		for _, o := range a.Outputs {
			rules = append(rules, outputRule{Target: o.Path, Source: a.Source, Output: o})
		}
	}

	sort.Slice(rules, func(i, j int) bool {
		if rules[i].Target == rules[j].Target {
			return rules[i].Source < rules[j].Source
		}
		return rules[i].Target < rules[j].Target
	})

	return rules
}

func appendCommentedCommands(b *strings.Builder, m *manifest.Manifest, r outputRule) {
	steps, err := render.ResolvePipelineWithOptions(m, r.Source, r.Output, render.ResolveOptions{CheckAvailability: false})
	if err != nil {
		// Keep unresolved notes as plain comments, not make recipes.
		b.WriteString("  # unresolved: ")
		b.WriteString(err.Error())
		b.WriteString("\n")
		return
	}

	commands := render.PlannedCommands(steps, render.BuildContext{
		InputPath:  r.Source,
		OutputPath: r.Target,
		Width:      r.Output.Width,
		Height:     r.Output.Height,
		ScaleMode:  r.Output.Options.ScaleMode,
		Background: r.Output.Options.Background,
		TmpPath:    "__tmp1__",
		Tmp2Path:   "__tmp2__",
	})
	for _, command := range commands {
		appendWrappedCommentCommand(b, command)
	}
}

func appendWrappedCommentCommand(b *strings.Builder, command string) {
	// Use non-tab comment lines so make does not treat these as recipes.
	parts, ops := splitCommandChain(command)
	if len(parts) == 0 {
		b.WriteString("  #\n")
		return
	}

	b.WriteString("  # ")
	b.WriteString(parts[0])
	b.WriteString("\n")

	for i, part := range parts[1:] {
		op := "&&"
		if i < len(ops) {
			op = ops[i]
		}
		b.WriteString("  # ")
		b.WriteString(op)
		b.WriteString(" ")
		b.WriteString(part)
		b.WriteString("\n")
	}
}

func splitCommandChain(command string) ([]string, []string) {
	if command == "" {
		return nil, nil
	}

	parts := make([]string, 0, 4)
	ops := make([]string, 0, 3)
	remaining := command

	for {
		idx, token := nextChainToken(remaining)
		if idx < 0 {
			parts = append(parts, strings.TrimSpace(remaining))
			break
		}

		parts = append(parts, strings.TrimSpace(remaining[:idx]))
		op := strings.TrimSpace(token)
		op = strings.ReplaceAll(op, " ", "")
		ops = append(ops, op)
		remaining = remaining[idx+len(token):]
	}

	if len(parts) > 0 && parts[0] == "" {
		parts[0] = command
	}

	return parts, ops
}

func nextChainToken(s string) (int, string) {
	tokens := []string{" && ", " || ", " | "}
	bestIdx := -1
	bestToken := ""

	for _, token := range tokens {
		idx := strings.Index(s, token)
		if idx >= 0 && (bestIdx == -1 || idx < bestIdx) {
			bestIdx = idx
			bestToken = token
		}
	}

	return bestIdx, bestToken
}
