# Generated by assets gen. DO NOT EDIT.
GENERATED_ASSET_FILES := out/images/anim_optimized.gif out/images/hero_1280.png out/images/hero_1280_crop.webp out/images/logo_256.png out/images/logo_256.webp out/images/logo_512_fill.jpg out/images/photo_1024.jpg

out/images/anim_optimized.gif: raw/test_gif.gif
  # gifsicle -O3 -b 'out/images/anim_optimized.gif'
out/images/hero_1280.png: raw/test_png.png
  # vips resize 'raw/test_png.png' 'out/images/hero_1280.png' 1
out/images/hero_1280_crop.webp: raw/test_png.png
  # vips resize 'raw/test_png.png' 'out/images/hero_1280_crop.webp' 1
out/images/logo_256.png: raw/test_svg.svg
  # resvg --width 256 --height 256 'raw/test_svg.svg' 'out/images/logo_256.png'
out/images/logo_256.webp: raw/test_svg.svg
  # resvg --width 256 --height 256 'raw/test_svg.svg' 'out/images/logo_256.webp'
out/images/logo_512_fill.jpg: raw/test_svg.svg
  # magick 'raw/test_svg.svg' -resize 512x512^ -gravity center -extent 512x512 'out/images/logo_512_fill.jpg'
out/images/photo_1024.jpg: raw/test_jpg.jpg
  # vips resize 'raw/test_jpg.jpg' 'out/images/photo_1024.jpg' 1

assets.lock: $(GENERATED_ASSET_FILES)
