# Generated by assets gen. DO NOT EDIT.
# Commands below are commented examples for readability in this file.
# Actual execution is performed via assets build --target <output>.
GENERATED_ASSET_FILES := assets/icons/icon_24.png assets/images/logo_64.png

assets/icons/icon_24.png: raw/icon.png
  # vips resize 'raw/icon.png' '__tmp1__.png' 1
  # oxipng -o 3 --strip safe --out 'assets/icons/icon_24.png' '__tmp1__.png'
assets/images/logo_64.png: raw/logo.svg
  # resvg --width 64 --height 64 'raw/logo.svg' '__tmp1__.png'
  # oxipng -o 3 --strip safe --out 'assets/images/logo_64.png' '__tmp1__.png'

assets.lock: $(GENERATED_ASSET_FILES)
